version: "3.9"

services:
  web:
    build:
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./.database:/var/opt/db
    environment:
      - DATABASE_URL=sqlite:////var/opt/db/ServerBlock.db
    command: >
      sh -c "alembic upgrade head
      && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
#      sh -c "gunicorn -k uvicorn.workers.UvicornWorker -w 4 -b 0.0.0.0:8000 app.main:app"
