from jinja2 import pass_context


@pass_context
def url_for(context: dict, name: str, **path_params) -> str:
    """
    Replace the HTTP scheme with HTTPS in the URL generated by the Flask function url_for.
    :param context: The context of the function call
    :param name: The mounted location to look through
    :param path_params: The path to the requested resource
    :return: URL for requested resource using HTTPS scheme
    """
    request = context["request"]
    http_url = request.url_for(name, **path_params)
    # If the request does not come from staging.campusenergie.nl do not change the scheme to https
    # (changing the scheme when running locally breaks getting the stylesheets)
    if "jojaba.nl" in str(request.url) and "jojaba.nl" not in str(request.url.path):
        return str(http_url).replace("http", "https", 1)
    return http_url
